In [ ]:
import sklearn
sklearn.show_versions()


System:
    python: 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
executable: /usr/bin/python3
   machine: Linux-6.1.85+-x86_64-with-glibc2.35

Python dependencies:
      sklearn: 1.6.0
          pip: 24.1.2
   setuptools: 75.1.0
        numpy: 1.26.4
        scipy: 1.13.1
       Cython: 3.0.11
       pandas: 2.2.2
   matplotlib: 3.8.0
       joblib: 1.4.2
threadpoolctl: 3.5.0

Built with OpenMP: True

threadpoolctl info:
       user_api: blas
   internal_api: openblas
    num_threads: 2
         prefix: libopenblas
       filepath: /usr/local/lib/python3.10/dist-packages/numpy.libs/libopenblas64_p-r0-0cf96a72.3.23.dev.so
        version: 0.3.23.dev
threading_layer: pthreads
   architecture: Haswell

       user_api: blas
   internal_api: openblas
    num_threads: 2
         prefix: libopenblas
       filepath: /usr/local/lib/python3.10/dist-packages/scipy.libs/libopenblasp-r0-01191904.3.27.so
        version: 0.3.27
threading_layer: pthreads
   architecture: Haswell

       user

# Preparing Data

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Feature Matrix (X)


In [ ]:
import pandas as pd
# Load dataset
data = pd.read_csv("/content/drive/MyDrive/AI_files/diabetes.csv")
# Feature matrix
X = data.drop(columns=["Outcome"]) # Drop target column
print(X.shape) # (n_samples, n_features)

(768, 8)


## Target Matrix (Y)

In [ ]:
# Target vector
y = data["Outcome"] # Extract target column
print(y.shape) # (n_samples,)

(768,)


## Limiting Classes

In [ ]:
# Limit classes to the first n_class (e.g., 2 classes)
n_class = 2
filtered_data = data[data["Outcome"] < n_class]
X = filtered_data.drop(columns=["Outcome"])
y = filtered_data["Outcome"]

# Data Pre-processing with scikit learn

In [ ]:
from sklearn.preprocessing import StandardScaler
# Example data
data = [[0, 0], [0, 0], [1, 1], [1, 1]]
# Initialize the transformer
scaler = StandardScaler()
# Step 1: Fit to the data (compute mean and std)
scaler.fit(data)
# Step 2: Transform the data
transformed_data = scaler.transform(data)
# Step 3: Alternatively, use fit_transform to do both steps at once
transformed_data_direct = scaler.fit_transform(data)

## Train-Test Split

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.25,
    train_size=None,# optional, can be set if test_size is None
    random_state=None,# Seed for the random number generator(for reproducibility)
    shuffle=True, # Whether or not to shuffle the data before splitting
    stratify=None # Ensures that the class distribution is similar in both train and test sets (useful for classification)
)

In [ ]:
from sklearn.model_selection import train_test_split
import numpy as np
# Example dataset
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
y = np.array([0, 1, 0, 1, 0])
# Split the dataset (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y,
 test_size=0.2, random_state=42)
print("X_train:", X_train)
print("X_test:", X_test)
print("y_train:", y_train)
print("y_test:", y_test)

X_train: [[ 9 10]
 [ 5  6]
 [ 1  2]
 [ 7  8]]
X_test: [[3 4]]
y_train: [0 0 0 1]
y_test: [1]


## Estimators Class in scikit learn

In [ ]:
class Estimator(object):
    def fit(self, X, y=None):
        """Fits estimator to data."""
        # Store the data to simulate learning
        self.X_ = X
        self.y_ = y
        return self
    def predict(self, X):
        '''Makes predictions using the learned data.'''
        # For this simple example, we are just going to return the same values from the training data
        # In a real estimator, this would involve applying a trained model to the new data X
        if not hasattr(self, "X_"):
             raise ValueError("Model has not been fitted yet.")
        return self.y_ # Returning the stored labels for demonstration purposes

## Example Build a KNN classifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
iris = load_iris()
X, y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
clf = KNeighborsClassifier(n_neighbors=5)
clf.fit(X_train, y_train)
print("Predictions for the first 5 samples:", clf.predict(X[:5]))
print("Class probabilities for the first 5 samples:", clf.predict_proba(X[:5]))

Predictions for the first 5 samples: [0 0 0 0 0]
Class probabilities for the first 5 samples: [[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


## Break Down the Code

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=42)
# Set hyper-parameters for the KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=5)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
clf = KNeighborsClassifier(n_neighbors=5)
clf.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y,
 test_size=0.3, random_state=42)
# Set hyper-parameters for the KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=5)
# Train the model using the training data
clf.fit(X_train, y_train)
# Make predictions using the test data
predictions = clf.predict(X_test)
print(predictions)
# Compute class probabilities for the test data
probabilities = clf.predict_proba(X_test)
print("Class probabilities for the test data:",
probabilities)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]
Class probabilities for the test data: [[0.  1.  0. ]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [0.  1.  0. ]
 [0.  0.  1. ]
 [0.  0.6 0.4]
 [0.  1.  0. ]
 [0.  0.2 0.8]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  0.8 0.2]
 [0.  0.  1. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  0.  1. ]
 [1.  0.  0. ]
 [0.  0.2 0.8]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [0.  0.  1. ]
 [0.  0.  1. ]
 [0.  0.  1. ]
 [0.  0.  1. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  0.4 0.6]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  0.2 0.8]
 [0.  0.8 0.2]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]]


# Regression Task


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
import pandas as pd
# Load dataset
data = pd.read_csv("/content/drive/MyDrive/AI_files/diabetes.csv")
print("First few rows of the dataset:")
print(data.head())
print("Dataset Info:")
print(data.info())

First few rows of the dataset:
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null 

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

## Handling missing values

In [6]:
columns_with_zeros = ['BloodPressure', 'Insulin', 'SkinThickness', 'BMI', 'Glucose']
for col in columns_with_zeros:
    data[col] = data[col].replace(0, data[col].median())

## Feature Matrix (X) and Target Vector (Y)

In [8]:
X = data.drop(columns=["BloodPressure"])
y = data["BloodPressure"]
print("Shape of Feature Matrix (X):", X.shape)
print("Shape of Target Vector (y):", y.shape)

Shape of Feature Matrix (X): (768, 8)
Shape of Target Vector (y): (768,)


## Splitting data

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("Training and Testing Sizes:")
print(f"X_train: {X_train.shape}, y_train: {y_train.shape}")
print(f"X_test: {X_test.shape}, y_test: {y_test.shape}")

Training and Testing Sizes:
X_train: (614, 8), y_train: (614,)
X_test: (154, 8), y_test: (154,)


## Train and Evaluate

In [11]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

In [16]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f'Mean Squared Error: {mse:.2f}')
print(f'R-squared: {r2:.2f}')

Mean Squared Error: 110.56
R-squared: 0.24


# Classification Task

## Loading the Dataset

In [17]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [18]:
import pandas as pd
d = pd.read_csv("/content/drive/MyDrive/AI_files/diabetes.csv")
print("First few rows of the dataset:")
print(d.head())

First few rows of the dataset:
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  


## Feature Matrix (X) and target Vector (y)

In [19]:
X = d.drop(columns=['Outcome'])
y = d['Outcome']
#Splitting the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Train the model

In [21]:
log_reg = LogisticRegression(max_iter = 1000)
log_reg.fit(X_train, y_train)
y_pred = log_reg.predict(X_test)

## Evaluating the model

In [24]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')
print(f'Precision: {precision:.2f}')
print(f'Recall: {recall:.2f}')
print(f'F1-Score: {f1:.2f}')

Accuracy: 0.75
Precision: 0.64
Recall: 0.67
F1-Score: 0.65
