## Worksheet_1

# Array Introduction

## Introducing Numpy

In [ ]:
import numpy as np
# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(7)
one_dim_array = np.array([4, 5, 6])
n_dim_array = np.array([[1, 2], [3, 4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
     # Print the array, dimensions, and data type
    print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")

Array:
7
Dimension: 0
Data type: int64

Array:
[4 5 6]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



## Array Dimensions: Shape and Reshape of Array:

In [ ]:
import numpy as np
# Create arrays of different dimensions
array_0d = np.array(5)
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# Print arrays with shapes
for i, arr in enumerate([array_0d, array_1d, array_2d, array_3d]):
    print(f"{i}D Array:\n{arr}\nShape: {arr.shape}\n")

0D Array:
5
Shape: ()

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)



In [ ]:
import numpy as np
# Create a 2-dimensional array with shape (2, 3)
array = np.array([[1, 2, 3], [4, 5, 6]])
# Reshape the array to have shape (3, 2)
reshaped_array = array.reshape(3, 2)
# Print  shape and  reshaped  of the array
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)

Original Shape: (2, 3) 
Reshaped Shape: (3, 2)


# Array Creation

## Using In-Built Function:

In [ ]:
a=np.arange(1, 10)
print(a)
x=range(1,10)
print(x)#x is an iterator
print(list(x))
#further arange examples:
x=np.arange(10.4)
print(x)
x=np.arange(0.5, 10.4,0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [ ]:
#50valuesbetween1and10:
print(np.linspace(1,10))
#7valuesbetween 1and10:
print(np.linspace(1,10,7))
#excludingtheendpoint:
print(np.linspace(1,10,7,endpoint=False))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


## Initializing Arrays with Ones,Zeros and Empty:

In [ ]:
import numpy as np
# Create arrays of specified shapes
ones_array = np.ones((2, 3)) # Shape: (2, 3)
zeros_array = np.zeros((3, 2)) # Shape: (3, 2)
empty_array = np.empty((2, 2)) # Shape: (2, 2)
identity_matrix = np.eye(3) # Shape: (3, 3)
print(ones_array, zeros_array, empty_array,
identity_matrix, sep='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[5.03483851e-310 0.00000000e+000]
 [1.22777155e-259 6.01347002e-154]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
# Existing Array of Shape:(2,3)
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Creating Array with Shape of existing array:
zeros, ones, empty = np.zeros(arr.shape), np.ones(
 arr.shape), np.empty(arr.shape) # Shape: (2,3)
print(arr, zeros, ones, empty, sep='\n')

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5.03483855e-310 0.00000000e+000 1.95619890e-153]
 [5.36531672e-080 2.12962892e-080 9.27363904e+242]]


## np.array

In [ ]:
import numpy as np
array_from_list = np.array([1, 2, 3]) # [1 2 3]
array_from_tuple = np.array((4, 5, 6)) # [4 5 6]
array_from_nested_list = np.array([[1, 2, 3], [4, 5,
6]]) # [[1 2 3] [4 5 6]]
print(array_from_list, array_from_tuple,
array_from_nested_list, sep='\n')

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


## other methods to create an Array

In [ ]:
array = np.array([1, 2, 3])
# Multiplies each element by 2, result: [2, 4, 6]
new_array = array * 2
# Creates a new array with the same elements
copied_array = np.copy(array)
# Slices elements from index 1 to 3, result:[2]
sliced_array = array[1:2]

In [ ]:
arr1 = np.array([[1, 2], [3, 4]]) # Shape: (2, 2)
arr2 = np.array([[5, 6], [7, 8]]) # Shape: (2, 2)
# Stacking examples
hstacked = np.hstack((arr1, arr2))
# Output hstack: [[1 2 5 6] [3 4 7 8]]
vstacked = np.vstack((arr1, arr2))
# Output vstack[[1 2] [3 4] [5 6] [7 8]]
colstacked = np.column_stack((arr1[0], arr2[0]))
# Output column stack: [[1 5] [2 6]]
print(hstacked, vstacked, colstacked, sep='\n')

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 5]
 [2 6]]


In [ ]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]]) # Shape: (2, 2)
arr2 = np.array([[5, 6], [7, 8]]) # Shape: (2, 2)
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
# Concatenate along axis 0 (vertical) Shape: (4, 2)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)
# Concatenate along axis 1 (horizontal) Shape: (2, 4)
print(concat_axis0, concat_axis1, sep='\n')

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


# Slicing and Indexing

In [ ]:
import numpy as np
# Arrays
arr1d = np.array([0, 1, 2, 3, 4, 5])
arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr3d = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]], [[8,
    9], [10, 11]]])
# Slicing examples
print("Basic:", arr1d[1:4], arr2d[1:3, 0:2], arr3d[1:2, 0:2,
    1:2])
# Output Basic: arr1d:[1 2 3] arr2d:[[3 4] [6 7]] arr3d :[[[5] [7]]]
print("Step:", arr1d[1:5:2], arr2d[::2, 1::2], arr3d[::2,
    ::2, 1::2])
# Output: Step: [1 3] [[1] [7]] [[[1] [9]]]

Basic: [1 2 3] [[3 4]
 [6 7]] [[[5]
  [7]]]
Step: [1 3] [[1]
 [7]] [[[1]]

 [[9]]]


# Array Math

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Add:", np.add(arr1, arr2)) # Output Add: [5 7 9]
print("Subtract:", np.subtract(arr1, arr2))
# Output Subtract: [-3-3-3]
print("Divide:", np.divide(arr1, arr2))
# Output Divide: [0.25 0.4 0.5 ]
print("Multiply:", np.multiply(arr1, arr2))
# Output Multiply: [ 4 10 18]
print("Power:", np.power(arr1, arr2))
# Output Power: [ 1 32 729]
print("Exp:", np.exp(arr1))
# Output Exp: [ 2.71828183 7.3890561 20.08553692]

Add: [5 7 9]
Subtract: [-3 -3 -3]
Divide: [0.25 0.4  0.5 ]
Multiply: [ 4 10 18]
Power: [  1  32 729]
Exp: [ 2.71828183  7.3890561  20.08553692]


In [ ]:
import numpy as np
# Define two matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
# Matrix multiplication using np.dot
result_dot = np.dot(A, B)
print("Result with np.dot:\n", result_dot) # Output shape:
(2, 2)

Result with np.dot:
 [[ 58  64]
 [139 154]]


(2, 2)

In [ ]:
import numpy as np
# Define two matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
# Matrix multiplication using @ operator
result_at = A @ B
print("Result with @ operator:\n", result_at) # Output shape: (2, 2)
# Matrix multiplication using np.matmul
result_matmul = np.matmul(A, B)
print("Result with np.matmul:\n", result_matmul) # Output shape: (2, 2)

Result with @ operator:
 [[ 58  64]
 [139 154]]
Result with np.matmul:
 [[ 58  64]
 [139 154]]


# Linear Algebra

In [ ]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])
print("Inverse:\n", np.linalg.inv(A))
# Output: Inverse: [[-2. 1. ], [ 1.5-0.5]]
print("Determinant:", np.linalg.det(A))
# Output: Determinant:-2.0
print("Frobenius Norm:", np.linalg.norm(A, 'fro'))
# Output: Frobenius Norm: 5.4772
print("2-Norm (Euclidean):", np.linalg.norm(A))
# Outptut: 2-Norm(Euclidean): 5.4772
print("Solution x:", np.linalg.solve(A, B))
#Output: Solution x: [-4. 4.5]

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004
Frobenius Norm: 5.477225575051661
2-Norm (Euclidean): 5.477225575051661
Solution x: [-4.   4.5]


# Tasks

## Problem 1: Array Creation:

In [ ]:
import numpy as np
#initialize empty array
arr_1 = np.empty((2,2))
print("Empty Array: \n", arr_1)

#initialize all ones array
arr_2 = np.ones((4, 2))
print("Ones Array: \n",arr_2)

arr_3 = np.full((2, 3), fill_value=7)
print("Array of given shape, type, and fill value: \n",arr_3)

arr_4 = np.array([[1, 2], [3, 4]])#2D array (given array)
zero_array = np.zeros_like(arr_4)
print("Array of Zeros with Same Shape as given Array: \n",zero_array)

ones_array = np.ones_like(arr_4)
print("Array of Ones with Same Shape as Given Array: \n",ones_array)

list1 = [1, 3, 5, 7]
numpy_array = np.array(list1)#converts list1 to a numpy array
print("List to Numpy Array: \n", numpy_array)

Empty Array: 
 [[4.78546283e-310 0.00000000e+000]
 [5.97819431e-322 6.60773269e-310]]
Ones Array: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Array of given shape, type, and fill value: 
 [[7 7 7]
 [7 7 7]]
Array of Zeros with Same Shape as given Array: 
 [[0 0]
 [0 0]]
Array of Ones with Same Shape as Given Array: 
 [[1 1]
 [1 1]]
List to Numpy Array: 
 [1 3 5 7]


## Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
arr1 = np.arange(10, 50) #range 10 to 49
print("Array with values ranging from 10 to 49: \n", arr1)

matrix_array = np.arange(9).reshape(3, 3)
print("3x3 Matrix with values ranging from 0 to 8: \n",matrix_array)

identity_matrix = np.eye(3)#eye - identity
print("Identity Matrix (3x3): \n",identity_matrix)
print(identity_matrix)

random_array = np.random.random(30)#array with random values
mean_value = random_array.mean()#using mean method
print("Random Array of size 30: \n", random_array)
print("Mean: \n", mean_value)

random_matrix = np.random.random((10, 10)) #10x10 array with random values
min_value = random_matrix.min()#min method
max_value = random_matrix.max()#max method
print("10x10 Random Array: \n",random_matrix)
print(random_matrix)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # 5th element (index 4)
print("\nZero Array with 5th Element Replaced with 1:")
print(zero_array)

# 7. Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_array = arr[::-1]
print("\nReversed Array:")
print(reversed_array)

# 8. Create a 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on Border and 0 Inside:")
print(border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[::2, 1::2] = 1  # Fill alternate columns in even rows
checkerboard[1::2, ::2] = 1  # Fill alternate columns in odd rows
print("\n8x8 Checkerboard Pattern:")
print(checkerboard)


 ## Problem- 3: Array Operations:

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
addition = x + y
print("Addition of x and y:")
print(addition)

# 2. Subtract the two arrays
subtraction = x - y
print("\nSubtraction of x and y:")
print(subtraction)

# 3. Multiply the array with an integer (e.g., 2)
multiplication = x * 2
print("\nMultiplication of x by 2:")
print(multiplication)

# 4. Square each element of the array
square = x ** 2
print("\nSquare of each element in x:")
print(square)

# 5. Find the dot product
dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)
print("\nDot product of v and w:", dot_v_w)
print("Dot product of x and v:")
print(dot_x_v)
print("Dot product of x and y:")
print(dot_x_y)

# 6. Concatenate x and y along rows; concatenate v and w along columns
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.vstack((v, w))
print("\nConcatenate x and y along rows:")
print(concat_xy_row)
print("Concatenate v and w along columns:")
print(concat_vw_col)

# 7. Concatenate x and v; observe error
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    concat_xv = str(e)
print("\nAttempt to concatenate x and v:")
print(concat_xv)


## Problem- 4: Matrix Operations:

In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("\nA * A^-1:")
print(identity)

AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:")
print(AB)
print("BA:")
print(BA)
assert not np.array_equal(AB, BA), "AB should not equal BA"

AB_transpose = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)
print("\n(AB)^T:")
print(AB_transpose)
print("B^T A^T:")
print(BT_AT)

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("\nSolution to the system of equations:")
print(X)

X_solve = np.linalg.solve(A, B)
print("\nSolution using np.linalg.solve:")
print(X_solve)


# Experiment

## Experiment 1: Element-wise Addition

In [ ]:
import numpy as np
import random
from timeit import timeit

# Define addition functions
def add_python(Z1, Z2):
    return [z1 + z2 for z1, z2 in zip(Z1, Z2)]

def add_numpy(Z1, Z2):
    return np.add(Z1, Z2)

# Generate random sample data
Z1 = random.sample(range(1000000), 1000000)
Z2 = random.sample(range(1000000), 1000000)

# Convert lists to NumPy arrays for NumPy operations
Z1_np = np.array(Z1)
Z2_np = np.array(Z2)

# Time the execution of each function
python_time = timeit("add_python(Z1, Z2)", globals=globals(), number=100)
numpy_time = timeit("add_numpy(Z1_np, Z2_np)", globals=globals(), number=100)

# Print results
print(f"Element-wise Addition:")
print(f"Pure Python addition: {python_time:.6f} s per loop")
print(f"NumPy addition: {numpy_time:.6f} s per loop")


Element-wise Addition:
Pure Python addition: 31.840199 s per loop
NumPy addition: 0.139148 s per loop


## Experiment 2: Element-wise Multiplication

In [1]:
import numpy as np
import random
from timeit import timeit

# Define multiplication functions
def multiply_python(Z1, Z2):
    return [z1 * z2 for z1, z2 in zip(Z1, Z2)]

def multiply_numpy(Z1, Z2):
    return np.multiply(Z1, Z2)

# Generate random sample data
Z1 = random.sample(range(1000000), 1000000)
Z2 = random.sample(range(1000000), 1000000)

# Convert lists to NumPy arrays for NumPy operations
Z1_np = np.array(Z1)
Z2_np = np.array(Z2)

# Time the execution of each function
python_time = timeit("multiply_python(Z1, Z2)", globals=globals(), number=100)
numpy_time = timeit("multiply_numpy(Z1_np, Z2_np)", globals=globals(), number=100)

# Print results
print(f"\nElement-wise Multiplication:")
print(f"Pure Python multiplication: {python_time:.6f} s per loop")
print(f"NumPy multiplication: {numpy_time:.6f} s per loop")



Element-wise Multiplication:
Pure Python multiplication: 45.537762 s per loop
NumPy multiplication: 0.176762 s per loop


## Experiment 3: Dot Product


In [ ]:
import numpy as np
import random
from timeit import timeit

# Define dot product functions
def dot_product_python(Z1, Z2):
    return sum(z1 * z2 for z1, z2 in zip(Z1, Z2))

def dot_product_numpy(Z1, Z2):
    return np.dot(Z1, Z2)

# Generate random sample data
Z1 = random.sample(range(1000000), 1000000)
Z2 = random.sample(range(1000000), 1000000)

# Convert lists to NumPy arrays for NumPy operations
Z1_np = np.array(Z1)
Z2_np = np.array(Z2)

# Time the execution of each function
python_time = timeit("dot_product_python(Z1, Z2)", globals=globals(), number=10)
numpy_time = timeit("dot_product_numpy(Z1_np, Z2_np)", globals=globals(), number=10)

# Print results
print(f"\nDot Product:")
print(f"Pure Python dot product: {python_time:.6f} s per loop")
print(f"NumPy dot product: {numpy_time:.6f} s per loop")



Dot Product:
Pure Python dot product: 3.319043 s per loop
NumPy dot product: 0.011454 s per loop


## Experiment 4: Matrix Multiplication

In [ ]:
import numpy as np
import random
from timeit import timeit

# Define matrix multiplication functions
def matrix_multiplication_python(A, B):
    return [[sum(a * b for a, b in zip(row, col)) for col in zip(*B)] for row in A]

def matrix_multiplication_numpy(A, B):
    return np.dot(A, B)

# Generate random 1000x1000 matrices for testing
A = [[random.randint(0, 10) for _ in range(1000)] for _ in range(1000)]
B = [[random.randint(0, 10) for _ in range(1000)] for _ in range(1000)]

# Convert lists to NumPy arrays for NumPy operations
A_np = np.array(A)
B_np = np.array(B)

# Time the execution of each function
python_time = timeit("matrix_multiplication_python(A, B)", globals=globals(), number=1)
numpy_time = timeit("matrix_multiplication_numpy(A_np, B_np)", globals=globals(), number=1)

# Print results
print(f"\nMatrix Multiplication:")
print(f"Pure Python matrix multiplication: {python_time:.6f} s")
print(f"NumPy matrix multiplication: {numpy_time:.6f} s")
